version: "2"
run:
  build-tags:
    - integration
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/joshjennings98)
    goimports:
      local-prefixes:
        - github.com/joshjennings98
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
