// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/joshjennings98/backend-demo/server/v2/server (interfaces: ICommandManager)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_server.go -package=mocks github.com/joshjennings98/backend-demo/server/v2/server ICommandManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	websocket "github.com/gorilla/websocket"
	gomock "go.uber.org/mock/gomock"
)

// MockICommandManager is a mock of ICommandManager interface.
type MockICommandManager struct {
	ctrl     *gomock.Controller
	recorder *MockICommandManagerMockRecorder
}

// MockICommandManagerMockRecorder is the mock recorder for MockICommandManager.
type MockICommandManagerMockRecorder struct {
	mock *MockICommandManager
}

// NewMockICommandManager creates a new mock instance.
func NewMockICommandManager(ctrl *gomock.Controller) *MockICommandManager {
	mock := &MockICommandManager{ctrl: ctrl}
	mock.recorder = &MockICommandManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICommandManager) EXPECT() *MockICommandManagerMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockICommandManager) Clear() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear")
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockICommandManagerMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockICommandManager)(nil).Clear))
}

// CloseWebsocketConnection mocks base method.
func (m *MockICommandManager) CloseWebsocketConnection() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseWebsocketConnection")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseWebsocketConnection indicates an expected call of CloseWebsocketConnection.
func (mr *MockICommandManagerMockRecorder) CloseWebsocketConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseWebsocketConnection", reflect.TypeOf((*MockICommandManager)(nil).CloseWebsocketConnection))
}

// IsRunning mocks base method.
func (m *MockICommandManager) IsRunning() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRunning")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRunning indicates an expected call of IsRunning.
func (mr *MockICommandManagerMockRecorder) IsRunning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRunning", reflect.TypeOf((*MockICommandManager)(nil).IsRunning))
}

// IsWebsocketConnected mocks base method.
func (m *MockICommandManager) IsWebsocketConnected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsWebsocketConnected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsWebsocketConnected indicates an expected call of IsWebsocketConnected.
func (mr *MockICommandManagerMockRecorder) IsWebsocketConnected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsWebsocketConnected", reflect.TypeOf((*MockICommandManager)(nil).IsWebsocketConnected))
}

// Run mocks base method.
func (m *MockICommandManager) Run(arg0 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockICommandManagerMockRecorder) Run(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockICommandManager)(nil).Run), arg0)
}

// SetWebsocketConnection mocks base method.
func (m *MockICommandManager) SetWebsocketConnection(arg0 *websocket.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetWebsocketConnection", arg0)
}

// SetWebsocketConnection indicates an expected call of SetWebsocketConnection.
func (mr *MockICommandManagerMockRecorder) SetWebsocketConnection(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWebsocketConnection", reflect.TypeOf((*MockICommandManager)(nil).SetWebsocketConnection), arg0)
}

// Stop mocks base method.
func (m *MockICommandManager) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockICommandManagerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockICommandManager)(nil).Stop))
}
