name: Tag and Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag-and-release:
    name: Tag and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          ref: main
          fetch-depth: 0 # get repo with all the tags

      - name: Increment tag
        run: |
          TAG="$(git describe --tags --abbrev=0 | awk -F. '{$(NF-1)+=1; OFS="."; print $1, $2, $3 }')"
          git tag $TAG
          git push origin $TAG
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: '~> v1'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
