name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        required: true
        description: Release type
        options: 
        - feature
        - bugfix

permissions:
  contents: write

jobs:
  tag-and-release:
    name: Tag and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          ref: main
          fetch-depth: 0 # get repo with all the tags

      - name: Increment tag
        run: |
          if [[ "${{ inputs.type }}" == "feature" ]]; then
            TAG="$(git describe --tags --abbrev=0 | sed 's|server/||g;s|cli/||g' | awk -F. '{$(NF-1)+=1; OFS="."; print $1, $2, 0 }')"
          elif [[ "${{ inputs.type }}" == "bugfix" ]]; then
            TAG="$(git describe --tags --abbrev=0 | sed 's|server/||g;s|cli/||g' | awk -F. '{$NF+=1; OFS="."; print $1, $2, $3 }')"
          else
            echo "::error ::Invalid release type"
          fi

          git tag $TAG
          git tag server/$TAG
          git tag cli/$TAG
          git push --tags origin
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: '~> v1'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
